### ISSUE TITLE
Question about the label of coloredMinist

### ISSUE THREAD

**Issue by Ma-Zijing** [reiinakano/invariant-risk-minimization#3]
Hi reiinakano, this is a fantastic work. I am trying to reproduce IRM with your codes. But there is a question about the labels of coloredMinist. Why do you assign a binary label y to the image based on the digit (y = 0 if digit < 5), and transform the problem to a binary classification problem? It seems the implemented codes cannot classify multiple classification problem, that is, the codes cannot recognize the specific digits of the images. Do I misunderstand the codes?
I am looking forward to your reply.

**Comment by reiinakano** [comment]
this is what is done in the paper
<img width="1009" alt="Screen Shot 2022-05-05 at 9 39 17 PM" src="https://user-images.githubusercontent.com/18363734/167068091-44a4512e-770f-4925-8046-d2f669535264.png">

**Comment by Ma-Zijing** [comment]
Oh I miss this description. Now I got it, thanks!
